hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000


key2: value2

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
